# Generated by Django 6.0.6 on 2026-06-08 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0002_add_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='savinggoal',
            index=models.Index(fields=['user', 'is_active'], name='sg_active_idx'),
        ),
        migrations.AddIndex(
            model_name='savinggoal',
            index=models.Index(fields=['user', 'status'], name='sg_status_idx'),
        ),
        migrations.AddIndex(
            model_name='savingtransaction',
            index=models.Index(fields=['user', 'date'], name='st_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='savingtransaction',
            index=models.Index(fields=['user', 'is_active'], name='st_active_idx'),
        ),
        migrations.AddIndex(
            model_name='savingtransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='st_type_idx'),
        ),
    ]
