# Generated by Django 6.0.5 on 2026-05-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_activitylog_note_whatiftransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SWITCH', 'Switch'), ('SAVING', 'Saving')], max_length=10),
        ),
        migrations.AlterField(
            model_name='whatiftransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SWITCH', 'Switch'), ('SAVING', 'Saving')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
