# Generated by Django 5.2.14 on 2026-05-27 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_activitylog_note_whatiftransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SWITCH', 'Switch'), ('SAVING', 'Saving')], max_length=10),
        ),
        migrations.AlterField(
            model_name='whatiftransaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('SWITCH', 'Switch'), ('SAVING', 'Saving')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'category', 'month', 'year', 'period'), name='unique_active_budget'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
