# Generated by Django 6.0.5 on 2026-06-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_add_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
