# Generated by Django 4.2.23 on 2026-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_add_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'timestamp'], name='al_user_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', 'action'], name='al_action_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'is_active'], name='budget_active_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'month', 'year'], name='budget_period_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='tx_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'transaction_type', 'money_type'], name='tx_type_money_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_active'], name='tx_active_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'is_pinned'], name='tx_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category', 'transaction_type', 'date'], name='tx_budget_idx'),
        ),
        migrations.AddIndex(
            model_name='whatiftransaction',
            index=models.Index(fields=['user', 'date'], name='wi_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='whatiftransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='wi_type_idx'),
        ),
    ]
