# Generated by Django 4.2.23 on 2026-06-13 12:16

from django.db import migrations, models


def blank_emails_to_null(apps, schema_editor):
    """Existing users have email='' (AbstractUser default). Convert to NULL so
    the unique constraint doesn't trip over multiple empty strings."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email='').update(email=None)


def null_emails_to_blank(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(email__isnull=True).update(email='')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        # Make email nullable first, normalize blanks to NULL, THEN add unique.
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.RunPython(blank_emails_to_null, null_emails_to_blank),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address'),
        ),
    ]
