# Generated by Django 6.0.4 on 2026-05-19 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('purple', 'Purple'), ('green', 'Green'), ('yellow', 'Yellow'), ('red', 'Red'), ('pink', 'Pink')], default='blue', max_length=10)),
                ('category', models.CharField(choices=[('important', 'Important'), ('goals', 'Goals'), ('reminder', 'Reminder'), ('ideas', 'Ideas'), ('archived', 'Archived')], default='ideas', max_length=20)),
                ('priority', models.CharField(choices=[('high', 'High'), ('med', 'Med'), ('low', 'Low')], default='med', max_length=10)),
                ('is_pinned', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
