"""
Django settings for money_log project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from dotenv import load_dotenv
from pathlib import Path

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4u)hc$wao_i_f1t)!7l1j8lz_vpdk37*sy!9akc!x5pmqnmb^y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = ["*"]

CSRF_TRUSTED_ORIGINS = [
    "https://money-logger.zeabur.app",
]

# LOAD SECURITY KEYS 

ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")
ENABLE_ENCRYPTION = os.getenv("ENABLE_ENCRYPTION", "false").lower() == "true"

PRODUCTION_MODE = os.getenv("PRODUCTION_MODE", "false").lower() == "true"

# reCAPTCHA (Google)
# Preferred env vars: RECAPTCHA_SITE_KEY / RECAPTCHA_SECRET_KEY
# Backward compatible: SITE_KEY / SECRET_KEY
RECAPTCHA_SITE_KEY = os.getenv("RECAPTCHA_SITE_KEY") or os.getenv("SITE_KEY")
RECAPTCHA_SECRET_KEY = os.getenv("RECAPTCHA_SECRET_KEY") or os.getenv("SECRET_KEY")
RECAPTCHA_ENABLED = os.getenv("RECAPTCHA_ENABLED", "true").lower() == "true"
RECAPTCHA_VERSION = os.getenv("RECAPTCHA_VERSION", "v2").lower()  # "v2" or "v3"
try:
    RECAPTCHA_MIN_SCORE = float(os.getenv("RECAPTCHA_MIN_SCORE", "0.5"))
except ValueError:
    RECAPTCHA_MIN_SCORE = 0.5

if not ENABLE_ENCRYPTION:
    if SECRET_KEY is None:
        raise Exception("ENABLE_ENCRYPTION is True but SECRET_KEY is not set")


AUTH_USER_MODEL = "accounts.User"


LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/login/"


# Authentication backends:
#  - EmailBackend: log in with email + password (custom login form)
#  - ModelBackend: Django default (admin / username), kept for fallback
#  - allauth: social login (Google)
AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailBackend",
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

# Google OAuth via django-allauth.
# Credentials come from Google Cloud Console -> APIs & Services -> Credentials
# -> "OAuth client ID" (Web application). NOT the reCAPTCHA keys.
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "APP": {
            "client_id": os.getenv("GOOGLE_CLIENT_ID", ""),
            "secret": os.getenv("GOOGLE_SECRET", ""),
            "key": "",
        },
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {"access_type": "online"},
        # Skip allauth's intermediate "Continue" page on social login.
        "OAUTH_PKCE_ENABLED": True,
    }
}

# allauth account behaviour (django-allauth 65.x format).
ACCOUNT_LOGIN_METHODS = {"username"}
# `email` MUST be listed here: allauth's social signup form always validates the
# email field's presence and raises ImproperlyConfigured on the Google signup
# step if it's missing. Our own (custom) signup view doesn't use these fields.
ACCOUNT_SIGNUP_FIELDS = ["username*", "email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "none"
# Social (Google) login: create the local account automatically and skip
# allauth's intermediate signup/confirm pages.
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
# Trust Google's verified email and mark our account email-verified (no OTP).
SOCIALACCOUNT_ADAPTER = "accounts.adapters.SocialAccountAdapter"


# Email (Gmail SMTP) — used to send signup verification OTPs.
# EMAIL_HOST_PASSWORD must be a Google "App Password" (Google Account → Security
# → 2-Step Verification → App passwords), NOT the normal Gmail login password.
# It is stored in .env as GMAIL_SMTP_PASSWORD. Google shows it with spaces
# ("abcd efgh ijkl mnop"); we strip them since SMTP wants the 16 chars only.
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "moneyloggerpage@gmail.com")
EMAIL_HOST_PASSWORD = (os.getenv("GMAIL_SMTP_PASSWORD") or "").replace(" ", "")
DEFAULT_FROM_EMAIL = f"Money Logger <{EMAIL_HOST_USER}>"

# OTP policy
OTP_EXPIRY_MINUTES = 10          # how long a code stays valid
OTP_RESEND_COOLDOWN_SECONDS = 60  # min wait between "resend code" requests


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.contrib.sites",
    # Google sign-in (OAuth) via django-allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "accounts",
    "dashboard",
    "ledger",
    "notes",
    "savings",
]

SITE_ID = 1

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.gzip.GZipMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

ROOT_URLCONF = "money_log.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ['templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.recaptcha_site_key",
            ],
        },
    },
]

WSGI_APPLICATION = "money_log.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases



if PRODUCTION_MODE:
    from urllib.parse import urlparse, parse_qsl

    # Replace the DATABASES section of your settings.py with this

    tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': tmpPostgres.path.replace('/', ''),
            'USER': tmpPostgres.username,
            'PASSWORD': tmpPostgres.password,
            'HOST': tmpPostgres.hostname,
            'PORT': 5432,
            'CONN_MAX_AGE': 600,
            'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
            # Neon's "-pooler" endpoint (PgBouncer transaction pooling) does not
            # keep server-side cursors alive between statements, which breaks
            # streaming queries like dumpdata/.iterator(). Disable them.
            'DISABLE_SERVER_SIDE_CURSORS': True,
        }
    }



else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"